### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by F1R3W4LL404** [Alvhix/ForwarderApp#1]
Any solution?
![image](https://user-images.githubusercontent.com/38119394/116754620-a9ad5c00-a9ce-11eb-9041-ddbe398bd2b3.png)

**Comment by alvhix** [comment]
This error is caused by not detecting the API_ID key in your environment variable. This app depends on TDLib which needs your API_ID and API_HASH and also some files to work that you need to put in the **lib/** folder. For more info about the setup go to the README.
