### ISSUE TITLE
Help to go

### ISSUE THREAD

**Issue by diegomustafamarino** [Alvhix/ForwarderApp#5]
Hello, i am a little bit newbie on Linux.
i did:
sudo docker pull alvhix/forwarder-app
and then, i don't know where i Make a separate folder, and where i can find the .env file and proceed...
Can you help me ?

**Comment by diegomustafamarino** [comment]
i installed docker, but i don't know what's it hehe...
I'm used to do simple python projects on windows, I would like to learn this part of linux.

**Comment by alvhix** [comment]
Hello, you can make the separate folder wherever you want in your system, the .env file is the file that you need to create with your Telegram credentials and can be obtained at the official [Telegram page](https://my.telegram.org/). All the applications need to have an api_id and api_hash, check this [documentation](https://core.telegram.org/api/obtaining_api_id) for more info.
Also, if you are very new to Docker I would suggest learning it first or you can just execute the project directly downloading the sources and executing it `python3 cli.py`. It can be executed in Linux or Windows, as you wish.

All this steps are explained in the [README](https://github.com/alvhix/forwarder-app#readme), make sure to check it out and if you have any specific doubt I will be happy to assist.

**Comment by diegomustafamarino** [comment]
Nice! Thx a lot! I will do it tomorrow.

**Comment by diegomustafamarino** [comment]
> Hello, you can make the separate folder wherever you want in your system, the .env file is the file that you need to create with your Telegram credentials and can be obtained at the official [Telegram page](https://my.telegram.org/). All the applications need to have an api_id and api_hash, check this [documentation](https://core.telegram.org/api/obtaining_api_id) for more info.
> Also, if you are very new to Docker I would suggest learning it first or you can just execute the project directly downloading the sources and executing it `python3 cli.py`. It can be executed in Linux or Windows, as you wish.
> 
> All this steps are explained in the [README](https://github.com/alvhix/forwarder-app#readme), make sure to check it out and if you have any specific doubt I will be happy to assist.

Did it. Trying on Windows, i created the .env file and checked the variables api id and api hash with prints. It's ok, but i got this problem:![20221228_174254~2.jpg](https://user-images.githubusercontent.com/97317367/209871406-912bf335-48c6-490e-a991-ca3eaab9caec.jpg)

**Comment by diegomustafamarino** [comment]
Looks like it's some problem setting tdlib parameters

**Comment by diegomustafamarino** [comment]
i still trying, the problem is here:
self.tdjson.send(
            {
                "@type": "setTdlibParameters",
                "database_directory": self.database_directory,
                "use_message_database": self.use_message_database,
                "use_secret_chats": self.use_secret_chats,
                "api_id": self.api_id,
                "api_hash": self.api_hash,
                "system_language_code": self.system_language,
                "device_model": self.device_model,
                "application_version": self.app_version,
                "enable_storage_optimizer": self.enable_storage_optimizer,
                "use_test_dc": self.use_test_dc,
                "use_file_database": self.use_file_database,
                "use_chat_info_database": self.use_chat_info_database,
            }
        )
        
but i don't know how to solve

**Comment by alvhix** [comment]
Download new version with pywtdlib 0.2.0 and try again, new TDLib version changed some parameters.

**Comment by diegomustafamarino** [comment]
Worked 100%
Now i have this problem:
![image](https://user-images.githubusercontent.com/97317367/210015214-1d8f1531-c52d-4fbd-94e8-f90799a067fb.png)

I am starring u, u are good

**Comment by diegomustafamarino** [comment]
simple solution:
def forward_messages(self, message) -> None:
        message_id = message.message_id
        source_id = message.source_id
        destination_ids = message.destination_ids
        options = message.options
        send_copy = message.send_copy
        remove_caption = message.remove_caption
        print(destination_ids)
        # forward messages
        self.client.forward_message(
            destination_ids,
            source_id,
            message_id,
            options,
            send_copy,
            remove_caption,
        )
        # log action
        self.logger.info(f"Message has been sent to the API: {message}")
        
        it worked for me, thx man, u are the best, i deserve the best for ur life, closing here.
